# Generated by Django 5.1.4 on 2024-12-05 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animal',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring', to='main.animal'),
        ),
        migrations.AddField(
            model_name='breed',
            name='animaltype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.animaltype'),
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.breed'),
        ),
        migrations.AddField(
            model_name='weighting',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.animal'),
        ),
        migrations.AlterUniqueTogether(
            name='weighting',
            unique_together={('animal', 'date')},
        ),
    ]
